### ISSUE TITLE
Not enough issue templates

### ISSUE THREAD

**Issue by chasm** [smooth-code/smooth-ui#100]
Your three issue templates don't cover all the types of issues. For example, I want to raise an issue about a matter of accessibility and your documentation. There is no obvious way to do that, so I am forced to go outside your templates, which means that my issue may be closed without comment. It seems a bit Kafkaesque. Surely, there are more than three types of issues.

**Comment by neoziro** [comment]
Hello @chasm, feel free to submit an issue out of existing templates, if it is important and relevant I will definitely consider it! Also feel free to submit a new issue template if you found it relevant. I don't close any issue without reading the content.
