### ISSUE TITLE
Using custom theme colors in ThemeProps

### ISSUE THREAD

**Issue by tfriem** [smooth-code/smooth-ui#104]
When adding a new color to a theme, it's not possible to use it in props like backgroundColor. Using it with the variant prop or inside the th() function with styled seems to work fine.

Did I hit a bug or is there a reason for this behavior?

Example: https://codesandbox.io/s/ql452yrz7j

**Comment by hoshomoh** [comment]
@neoziro just calling your attention to this. Or you can point me in the right direction and I can try to make a PR

**Comment by neoziro** [comment]
It is fixed in v11, theme is now merged correctly.
