### ISSUE TITLE
`ThemeProvider` is not in exported typings

### ISSUE THREAD

**Issue by xeoneux** [smooth-code/smooth-ui#109]
## 🐛 Bug Report

The dist has no exported member `ThemeProvider`

## To Reproduce

Try `import { ThemeProvider } from "@smooth-ui/core-sc";` in a `.tsx` file

## Expected behavior

Typings for `ThemeProvider` to exist! 😄

**Comment by ReasonableDeveloper** [comment]
@nc9 I'm not getting the typescript error when importing it from `emotion-theming` instead of `@smooth-ui/core-sc`. Unfortunately, the theme is is only working for me when importing from the latter.

**Comment by neoziro** [comment]
Feel free to submit a PR to fix it.

**Comment by neoziro** [comment]
Types are no longer part of this library, please add them to https://github.com/DefinitelyTyped/DefinitelyTyped.
