### ISSUE TITLE
Col offset not implmented in TypeScript

### ISSUE THREAD

**Issue by GuillaumeDesforges** [smooth-code/smooth-ui#113]
## 🐛 Bug Report

When using @smooth-ui/core-sc with TypeScript (v 9.0.1), one cannot add an offset to a `Col` in a `Row` in a `Grid`.

## To Reproduce

* Create a TypeScript project with TSLint
* Install @smooth-ui/core-sc version 9.0.1
* Create a simple component with `Grid`, `Row`, `Col`
* Try to set property `oxs` or related to any value
* TSLint highlights a TS2322 error.

## Expected behavior

According to documentation an JavaScript implementation, `Col` should have offset properties.

## Possible fix

The JS properties are defined here:
https://github.com/smooth-code/smooth-ui/blob/ef92be3088183f26bf486a6a235e4a1c54266a88/packages/shared/core/Col.js#L139

The TS definition of ColProps is here:
https://github.com/smooth-code/smooth-ui/blob/ef92be3088183f26bf486a6a235e4a1c54266a88/packages/shared/core/index.d.ts#L262

**Comment by neoziro** [comment]
Hello @GuillaumeDesforges, thanks for reporting. Help is welcome.

**Comment by rlax** [comment]
In addition to my PR fixing this issue, there are more errors in `.d.ts` when we compare it to PropTypes (i.e. boolean `sm`, `xs` values...)

What approach do we choose when solving related problems? I can propose creating and fixing issues or maybe some kind of milestone for ts/propTypes consistency.
