### ISSUE TITLE
Using gradient with variants?

### ISSUE THREAD

**Issue by muhajirdev** [smooth-code/smooth-ui#119]
Hi there, awesome project.

I have a question. I am trying to put this in primary variant.
```
primary: linear-gradient(to right, #C06C84, #6C5B7B, #355C7D);
```

which seems not working. Maybe because it's using backgroundColor instead of background.

**Comment by muhajirdev** [comment]
Also, I think it would be better if variant is not just based on color. For example, `boxShadow` maybe some people want variant primary with color + boxShadow.

**Comment by neoziro** [comment]
Hello @muhajirdev, thanks for this issue. Yes `variants` are not very good actually, we have to polish them. I will try to find a generic solution to solve these kind of problems.

**Comment by neoziro** [comment]
Only color variants are supported in v11. If you want to do so, you have to add custom style to the component.
