### ISSUE TITLE
Switch to emotion css?

### ISSUE THREAD

**Issue by rockmandash** [smooth-code/smooth-ui#12]
Since emotion css is faster than styled-components, I think you can get some performance by just switching to react-emotion.
If I am wrong please correct me.

**Comment by neoziro** [comment]
Yes I know, but Styled Components v4 should solve it! The better should be to have the choice between the two but it is very complicated and not for now!

**Comment by neoziro** [comment]
@rockmandash good news, https://github.com/smooth-code/smooth-ui/releases/tag/v5.0.0
