### ISSUE TITLE
styled-system

### ISSUE THREAD

**Issue by viczam** [smooth-code/smooth-ui#121]
Why isn't smooth-ui using [styled-system](https://styled-system.com) already? It seems like the effort is duplicated right now.
On top of that, styled-system comes with a pretty good theme specification.

Btw, I think you've done an amazing job so far with smooth-ui!

**Comment by neoziro** [comment]
Hello @viczam, styled-system is not fully compatible yet with what I want to achieve. It is plan to add missing feature into styled-system to be able to use it!

**Comment by viczam** [comment]
I've actually noticed that you're doing a couple of things better (like class duplication to increase specificity). On top of that, you're following the theme specification as well (which I thought it's not happening).
Bottom line - I like better the styled-system from smooth-ui :)
Again, thank you very much guys for what you've been able to do so far!

**Comment by neoziro** [comment]
Even if projects are not merged, I will stick to theme convention imposed by styled-system (eg. space and not spaces). I will do it in next major.
