### ISSUE TITLE
a question about docz

### ISSUE THREAD

**Issue by HadeAs** [smooth-code/smooth-ui#125]
hi, I have a componet API doc used docz, i have a question when used it.
I can't use experimental class properties, when defining a class in Playground
```
SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties' (5:12)
```

I tried this `doczrc.js`:
```
export default {
  classProperties: true, // not working
  modifyBabelRc: babelRc => ({
    ...babelRc,
    plugins: [
      ...babelRc.plugins,
      '@babel/plugin-proposal-class-properties', // neither working
    ],
  }),
}
```

Create a new Playground like this:
```
<Playground>
  () => {
    class WithState extends React.Component {
      state = { // this causes the error
        text: 'hi'
      }

      render() {
        return <div>{this.state.text}</div>
      }
    }
}
</Playground>
```

```
Failed to compile.

./src/components/index.mdx
SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties' (5:12)
```

**Comment by HadeAs** [comment]
I saw your doc used classProperties(eg: Modal component),  so pls help me.

**Comment by neoziro** [comment]
Hello @HadeAs, docz is kind of magical. I don’t exactly know why it is working for me and not for you. I suggest you to submit a new issue on docz. But I think you should wait for v1, before doing anything.

**Comment by HadeAs** [comment]
> Hello @HadeAs, docz is kind of magical. I don’t exactly know why it is working for me and not for you. I suggest you to submit a new issue on docz. But I think you should wait for v1, before doing anything.

ok  thanks
