### ISSUE TITLE
Missing Tooltip type

### ISSUE THREAD

**Issue by gagandeepgill** [smooth-code/smooth-ui#127]
## 🐛 Bug Report

Missing `Tooltip` exported type.

## To Reproduce

1. Try `import { Tooltip } from "@smooth-ui/core-em";` in a `.tsx` file

## Link to repl or repo (highly encouraged)

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @smooth-ui/core-sc,@smooth-ui/core-em,styled-components,@emotion/core,@emotion/styled,emotion-theming --markdown --clipboard`

Paste the results here:

```bash

```

**Comment by neoziro** [comment]
I don't write TypeScript type, a PR is welcome to fix it.

**Comment by neoziro** [comment]
Types are no longer part of this library, please add them to https://github.com/DefinitelyTyped/DefinitelyTyped.
