### ISSUE TITLE
Can I specify mount node with Modal

### ISSUE THREAD

**Issue by midnightcodr** [smooth-code/smooth-ui#129]
With `semantic-ui-react`, I am able to specify where to mount a modal in the DOM using attribute `mountNode`, is there something similar I can use with smooth-ui? The reason I am asking is because I have the following workflow in one of my projects.

Start with a form with some text fields and a preview button. When the preview button is clicked, a modal opens with some terms and conditions text, a checkbox for user to consent and a button to submit. Now the problem is since the modal is mounted outside of the form (it's actually outside `div#root`), the submit button doesn't work anymore because it does not live inside the form. With SUR and its mountNode the problem is quite easy to fix but I am out of luck with smooth-ui. Anyone has an idea? Thanks.

**Comment by neoziro** [comment]
Hello @midnightcodr, for now you can't. I suggest you to create a fake button and submit the form manually. Anyway modals have to be outside the root if you want a correct display. Else any "relative" position will break it. So it is probably better to choose another solution.
