### ISSUE TITLE
Slider component

### ISSUE THREAD

**Issue by IcanDivideBy0** [smooth-code/smooth-ui#13]
Any thought on adding a slider component ? something similar to https://material-ui.com/lab/slider/

I'd be happy to contribute if there is a place for this type of component :)

**Comment by neoziro** [comment]
@IcanDivideBy0 of course! Feel free to add it ;)

**Comment by neoziro** [comment]
Unfortunately it will not happen! v11 is a complete rewrite, maybe maybe not, anyway I close it.
