### ISSUE TITLE
Add "cursor: disabled;" for Button component while disabled

### ISSUE THREAD

**Issue by warrenmcquinn** [smooth-code/smooth-ui#131]
## 🚀 Feature Proposal
Currently, `<Button disabled />` uses the "cursor: pointer;" style property, and I propose that this should be changed to "cursor: disabled;".

## Motivation

This library is awesome, and this is a little tweak to improve accessibility. The `disabled` prop's semi-opaque style doesn't really shout "don't click me".

**Comment by viczam** [comment]
Is there such a thing as `cursor: disabled;`? Maybe `cursor: not-allowed;`.

**Comment by neoziro** [comment]
In fact a button should not have the `cursor: pointer;` by default. But if disabled, I think using the default cursor is a good choice: https://codesandbox.io/s/1xpzoqwmj

Could someone submit a PR to fix it?

**Comment by jyash97** [comment]
Hey @neoziro Can I take this up ?

**Comment by neoziro** [comment]
@jyash97 feel free!
