### ISSUE TITLE
Broken when using nested theme properties

### ISSUE THREAD

**Issue by 1natsu172** [smooth-code/smooth-ui#134]
### Broken when using properties nested in the theme object.

At `@smooth-ui` version `10.0.7`

_**Error message**_

> Couldn't parse the color string. Please provide the color as a string in hex, rgb, rgba, hsl or hsla notation.

## To Reproduce

* Define colors object for theme.

```javascript
const colors = {
  skyBlue: '#fff',
  paleVio: 'palevioletred'
}
```

* Create **nested** properties theme object

example of bug

```javascript
// Cause an error
const theme = {
  colors
}
```

* Create **non nested** properties theme object

example of work fine.

```javascript
// Work fine
const theme = {
  ...colors
}
```

## Expected behavior

Should work even if the theme object is deep.

## Link to repl or repo (highly encouraged)

Codesandbox: https://codesandbox.io/embed/n0vxz7j0om

> Look both `<BugThemeExample />` and `<WorkThemeExample />`

**Comment by neoziro** [comment]
In fact, Smooth UI already uses `theme.colors`, you have to specify the default one from Smooth UI. See this updated example: https://codesandbox.io/s/k14xmwow95.

We should definitively explain it in the documentation.

**Comment by 1natsu172** [comment]
Ah I see. It conflicts with the default theme of Smooth-UI.
Thank you for telling the solution of sandbox example.
