### ISSUE TITLE
Modal is closing when moving mouse selection outside container

### ISSUE THREAD

**Issue by pippo111** [smooth-code/smooth-ui#137]
## 🐛 Bug Report

Modal box is closing unexpectedly when moving mouse selection outside container.

## To Reproduce

Open modal box, select some text and with active selection move mouse pointer outside of modal's container, then release mouse button. See:

![smoothui-modal-bug](https://user-images.githubusercontent.com/22401020/57295607-2e5c8c80-70cb-11e9-99a8-0cb1a2413bb3.gif)

## Expected behavior

Selection should persist and modal should remain open. It is frustrating especially when selecting text on the input box and modal suddenly closes.

```bash
## System:
 - OS: Linux 4.19 Manjaro Linux
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 5.16 GB / 15.51 GB
 - Container: Yes
 - Shell: 3.0.2 - /usr/bin/fish
## Binaries:
 - Node: 11.14.0 - /usr/bin/node
 - Yarn: 1.15.2 - /usr/bin/yarn
 - npm: 6.9.0 - /usr/bin/npm

```

**Comment by neoziro** [comment]
Hello @pippo111, hmm yes I think it should not be the behaviour, it is actually a bug.

**Comment by neoziro** [comment]
Modal is gone in new release, please use [Reakit Dialog](https://reakit.io/docs/dialog/) instead.
