### ISSUE TITLE
Grid Cols not taking 100% width on mobile

### ISSUE THREAD

**Issue by ancashoria** [smooth-code/smooth-ui#143]
## 💥 Regression Report

Grid Columns were taking the whole width on mobile, but now they just split the available space.

## Last working version

Worked up to version:

Stopped working in version:

## To Reproduce

```
<Grid>
  <Row>
    <Col>left</Col>
    <Col>right</Col>
  </Row>
</Grid>
```

## Expected behavior

The columns should be displayed one under the other instead of side by side

https://upbeat-noyce-c884dc.netlify.com/

```bash
## System:
 - OS: macOS 10.14.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 210.15 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 11.0.0 - ~/.nvm/versions/node/v11.0.0/bin/node
 - Yarn: 1.13.0 - ~/.nvm/versions/node/v11.0.0/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v11.0.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - @smooth-ui/core-sc: ^10.1.0 => 10.1.0 
 - styled-components: ^4.2.1 => 4.2.1 
```

I hacked it by using `<Col xs={12} md={6}>` but it's really not ideal.

Thanks

**Comment by neoziro** [comment]
This is the excepted behaviour. By default, Col has a `flex: 1`. If you want full width, use `xs={12}`.

**Comment by ancashoria** [comment]
Got it,
thanks for letting me know.

**Comment by ancashoria** [comment]
Also, great work on this library, it's a joy to use
