### ISSUE TITLE
Popover add 'trigger'('click' | 'hover') prop  and 'animation' 

### ISSUE THREAD

**Issue by rumsky** [smooth-code/smooth-ui#146]
## 🚀 Feature Proposal

Popover add 'trigger'('click' | 'hover') prop and 'animation'

## Motivation
trigger open by clicking or hovering
add animation effect to popup

**Comment by neoziro** [comment]
Popover is gone in v11, please migrate to [Reakit Popover](https://reakit.io/docs/popover/).
