### ISSUE TITLE
Is it possible to have a migration documentation particularly for Grid System components ?

### ISSUE THREAD

**Issue by vripoche** [smooth-code/smooth-ui#150]
Hello,

We use a lot SmoothUI in our products, and you know it ;-), the new version should be really nice but we are a little bit afraid about the amount of components which are disappeared.
I read that we can found most of them in Reakit but `Grid` is not inside for example.

Is it possible to have a migration documentation page with your advices for each disappeared components and how it can be migrated (in Smooth UI a Col was a Box for example, but not in other Grid System libraries) ?

Could you also push online the old v10 documentation, it is just really useful because we cannot migrate all our products in a same time and we still need it for months ?

Thank you guys.

**Comment by neoziro** [comment]
Hello @vripoche,

`Grid` is the missing one yes, I plan to add it in Smooth UI, in the meantime, it is very easy to reimplement: https://github.com/smooth-code/smooth-ui/blob/v10.1.0/packages/shared/core/Grid.js#L29

About `Row` and `Col`. They are still present but everywhere as [`row` and `col` prop](https://www.smooth-code.com/open-source/xstyled/docs/system-props/#xgrids).

About `Dialogs`, `Popover` and `Tooltip` they are all in [Reakit](https://reakit.io/) with a better implementation.

In the meantime I don't have time to republish the old documentation and to create a migration guide. But I will do it as soon as possible.

Migrating to xstyled would be a great addition for you, it is faster, compliant to [system-ui spec.](https://system-ui.com/theme/) and even more flexible than before.

**Comment by vripoche** [comment]
Hi,

Thank you for your fast feedback.

I have answers now ;-) We will study more accurately the xstyled documentation and we will be very grateful If you find time to create a migration guide, I am sure it will be very useful for all SmoothUI users.
