### ISSUE TITLE
Lines prop takes up more space than it needs in Text component

### ISSUE THREAD

**Issue by CodingDive** [smooth-code/smooth-ui#166]
First of all, I'd like to thank you for all the hard work on smooth-ui. It's one of my favorite component libraries!

## 🐛 Bug Report
```jsx
<Text lines={10}>
  Short text fitting in one line
</Text>
```

Is taking up 10 lines of space. Most of which are rendered as white space.

## To Reproduce

Go to the [docs](https://www.smooth-code.com/open-source/smooth-ui/docs/text/#ellispis--multilines) and increment the value of the `lines` prop. You'll see white space being added.

In the example from the docs, two lines look great. 
![image](https://user-images.githubusercontent.com/28842311/75147049-b7958c00-56fc-11ea-9d31-aa2eb0451b7d.png)

When incrementing the value, more whitespace is added.

![image](https://user-images.githubusercontent.com/28842311/75146982-8d43ce80-56fc-11ea-9066-0b1578403c81.png)

## Expected behavior

I expected the line prop to only take up as much space as the text needs or cut it off.

## Env

```bash
"@smooth-ui/core-sc": "^11.1.5",

## System:
 - OS: Windows 10 10.0.17763
 - CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
 - Memory: 18.50 GB / 31.92 GB
## Binaries:
 - Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.0 - C:\Program Files\nodejs\yarn.CMD
 - npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by gregberge** [comment]
This is the expected behaviour. If you specify a number of lines it measure the number of lines. It is not possible to implement what you are asking for without JavaScript. You should probably use a library to crop text and add `...`.

**Comment by CodingDive** [comment]
`<Text>` is a React component so adding some more JS shouldn't be a problem. Would you accept a PR for this or would you rather have me implement this in user land?

**Comment by gregberge** [comment]
@CodingDive yeah if it is perf I am open for a PR to fix it!
