### ISSUE TITLE
Docs broken

### ISSUE THREAD

**Issue by corysimmons** [smooth-code/smooth-ui#174]
![image](https://user-images.githubusercontent.com/224636/79550902-f560c200-8066-11ea-9c02-ee47485c1664.png)

![image](https://user-images.githubusercontent.com/224636/79550925-fc87d000-8066-11ea-88e4-562dc01539ce.png)

**Comment by martinmares** [comment]
This urls works ok:

https://smooth-ui.netlify.app/docs/getting-started/
https://smooth-ui.netlify.app/docs/introduction/
...

But every links on every pages is broken. Example of broken links:

https://smooth-ui.netlify.app/open-source/smooth-ui/docs/getting-started/
https://smooth-ui.netlify.app/open-source/smooth-ui/docs/introduction/
...

**Comment by gajewsky** [comment]
The docs are not accessible for couple days already. Maybe it would be a good idea to have it shipped to some alternative place as backup just in case

**Comment by corysimmons** [comment]
I just clicked on this link.. It's still broken.

![image](https://user-images.githubusercontent.com/224636/79782875-bd2edd00-830d-11ea-9b6f-b891a8143ed9.png)

I will _never_ understand why people don't just do their docs in Gitbook with CodeSandbox links.

**Comment by gajewsky** [comment]
@corysimmons @martinmares Since docs still don't work I forked repo and deployed it to gh-pages. Thought it might be a temporary help for you guys :)

https://gajewsky.github.io/smooth-ui/docs

**Comment by cyrilchapon** [comment]
Super helping; I was at the point just before getting frustrating (coming a week later).
We need docs back though !

**Comment by cyrilchapon** [comment]
@gajewsky did you fix something ? Maybe a PR ?

**Comment by gajewsky** [comment]
Hey @cyrilchapon nope, just pulled repo and then deployed it. Some hosting issues probably. BTW I decided to move on and use some alternative ui framework

**Comment by dhenson02** [comment]
@gajewsky dont blame you.  unfortunate how lacking the docs are and a lot of props dont pass down like you would expect.  

was fun playing with it tho :)

**Comment by shivjsdev** [comment]
@gajewsky would you mind to specify which alternative ui framework you use now? Thanks.

**Comment by gajewsky** [comment]
@shivjsdev I went with https://github.com/mui-org/material-ui :)

**Comment by aadamsx** [comment]
@gajewsky why go with Material and now another Styled-Components based framework?

**Comment by imdevan** [comment]
Still broken :'(

**Comment by gregberge** [comment]
Hello, Smooth UI could start again one day. Currently it is not maintained. If someone submit a PR to fix docs (pointing to https://gajewsky.github.io/smooth-ui/docs/getting-started/ should be good). Then I will merge it.

**Comment by Omar-Aziz** [comment]
![Kapture 2021-07-30 at 14 27 48](https://user-images.githubusercontent.com/23618431/127702767-f73325d0-e562-4a13-8bce-2f4e477f953f.gif)

Still

**Comment by gregberge** [comment]
As I said, Smooth UI is deprecated.
