### ISSUE TITLE
Handle Input refs

### ISSUE THREAD

**Issue by pt-br** [smooth-code/smooth-ui#23]
Hi!

I've already find out how to handle it by reading your src code, so my issue is more like an advise than an issue itself.

Pls write somewhere that you're handling the refs with `baseRef` - as a styled-components user, I was trying to pass the `innerRef` prop.

Thanks!

**Comment by neoziro** [comment]
Yeah I should update documentation about that specific point. Thanks!

**Comment by neoziro** [comment]
@pt-br it is fixed in v5, you can now use `innerRef`.
