### ISSUE TITLE
Modals should "manage" focus

### ISSUE THREAD

**Issue by theKashey** [smooth-code/smooth-ui#26]
Any "focused task" should trap __focus__ inside, and not let it get out.

Right now:
1. It does not set a focus on modal content, keeping it on the button one clicked to open a modal
2. Does not prevent leaving modal. "tabbing-out" from it.
3. Lucky we - it closes modal on any action "outside"

https://github.com/theKashey/react-focus-lock will do the job :)

**Comment by neoziro** [comment]
Yes modal have some issues. I will take a look, thanks!
