### ISSUE TITLE
Labels inside a switch are considered bad UX

### ISSUE THREAD

**Issue by AlexandreBroudin** [smooth-code/smooth-ui#53]
Without talking accessibility issues,
It is unclear whether the label (‘ON’ for example) is the current state, or the action.

The solution is to place the label outside the switch.

https://github.com/smooth-code/smooth-ui/blob/eba4b7e2078aab4d640cc75f6160f6e7c6976558/docs/components/Switch.mdx#L26

**Comment by neoziro** [comment]
Are you sure about that? In iOS you can add labels to switches and it is inside the switch.

**Comment by neoziro** [comment]
I think we could notice it in documentation, but even if it is a bad practice, I think it is a common UI thing.

**Comment by neoziro** [comment]
I choose to let them, but by default they are not present.
