### ISSUE TITLE
GettingStarted doc should invoke globalStyle?

### ISSUE THREAD

**Issue by edmundito** [smooth-code/smooth-ui#54]
Hello, I was wondering if you could clarify something about the documentation:

https://github.com/smooth-code/smooth-ui/blob/eba4b7e2078aab4d640cc75f6160f6e7c6976558/docs/GettingStarted.mdx#L40

The way I got the global style to work correctly is by invoking globalStyle first:
```js
injectGlobal(globalStyle())
```

Is this a mistake in the doc or is there something I a missing?

In any case, it seems that `injectGlobal` will be deprecated in styled-components v4:
https://www.styled-components.com/docs/api#injectglobal

**Comment by neoziro** [comment]
The correct call is `injectGlobal\`${globalStyle()}\``

I am waiting for styled-components v4 + emotion v10 to be released to change this.

**Comment by neoziro** [comment]
No longer relevant in v11.
