### ISSUE TITLE
Page Crashes on multiple pages: Textarea, Typography, Custom component

### ISSUE THREAD

**Issue by thevangelist** [smooth-code/smooth-ui#67]
Tried to open documentation with Chrome: https://smooth-ui.smooth-code.com/docs-components-textarea for example crashes, such as "typography" and "custom component" pages.

Result:

![screen shot 2018-10-23 at 15 06 05](https://user-images.githubusercontent.com/3482617/47359341-2f9d0d80-d6d5-11e8-8df0-2a76745c2116.png)

**Comment by neoziro** [comment]
It is fixed, sorry.
