### ISSUE TITLE
Col unexpectedly wraps when uses breakpoints 

### ISSUE THREAD

**Issue by avatar5555555** [smooth-code/smooth-ui#70]
Example on (codesandbox) [https://codesandbox.io/s/6jk1nq0x8z](https://codesandbox.io/s/6jk1nq0x8z). If try to resize the window col's won't fit as expected (On 'sm' breakpoint 2 rows, on 'md' 1 row).

**Comment by neoziro** [comment]
You have no the correct `box-sizing`, you can inject [global normalize](https://smooth-ui.smooth-code.com/docs-getting-started#global-normalize-recommended) or you can add:

```
* {
    box-sizing: border-box;
}
```

**Comment by avatar5555555** [comment]
It works, thanks a lot! Sorry fo my inattention.
