### ISSUE TITLE
Inputs render with error state already assumed

### ISSUE THREAD

**Issue by valcho** [smooth-code/smooth-ui#71]
First, thanks for the awesome style library! 

I'd like to report an issue I encountered with [this demo](https://codesandbox.io/s/40o45po3l4) where Smooth UI is used with React final form. The issue is that the input fields already come with an error state and are displayed as red. 

Tried to debug the issue on my own, but couldn't figure it out on my own.

**Comment by neoziro** [comment]
Hello @valcho , `valid` should be `false` at start, you must do: `touched ? valid : undefined` instead of just passing `valid`. It should solve your problem.
