### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by gtbremer** [smooth-code/smooth-ui#72]
Unless I've missed it somewhere, the documentation does not make it clear what browsers are fully supported by Smooth UI. If this exists in the current docs, can you please point me in the right direction? Thanks!

**Comment by neoziro** [comment]
Hello @gtbremer, yeah I think it is something that is missing in the documentation.

All browsers supported by Styled Components are supported:

https://www.styled-components.com/docs/faqs#which-browsers-are-supported

**Comment by gtbremer** [comment]
Thanks for the info!
