### ISSUE TITLE
Document browser compatibility

### ISSUE THREAD

**Issue by neoziro** [smooth-code/smooth-ui#73]
As pointed in #72, we should document the browser compatibility on the website.

Actually, we rely on [browsers supported by Styled Components](https://www.styled-components.com/docs/faqs#which-browsers-are-supported) or browsers supported by emotion (probably the same).

This issue consist by adding a new FAQ section on the website, same as Styled Components.

**Comment by srdmathur** [comment]
I would like to take this up. Can you help me with starting the project on local machine. 
upon "**npm run dev**" after "**npm install**", its throwing error : 

 ERROR  Failed to compile with 29 errors                                                                                17:32:27
This dependency was not found:

* @smooth-ui/core-sc in ./docs/Home.mdx, ./docs/GettingStarted.mdx and 27 others

To install it, you can run: npm install --save @smooth-ui/core-sc

**Comment by neoziro** [comment]
Please use `yarn` instead of npm. I will add a CONTRIBUTING.md file to fix this problem.

**Comment by srdmathur** [comment]
I am still facing the same issue.

**Comment by neoziro** [comment]
@srdmathur you have to run `yarn build:watch` in background, sorry.
