### ISSUE TITLE
Is there a way of adding a custom prop to a component relying on system utilities (like responsiveness)

### ISSUE THREAD

**Issue by rafaelchiti** [smooth-code/smooth-ui#78]
I'm trying to add a custom prop to Box (`flexGrow`). I would like flexGrow to inherit the benefits that other props have in smooth-ui system (in this case responsive behavior). 
In styled system you would use https://github.com/jxnblk/styled-system/blob/master/docs/api.md#customize
Is there a way to extend Box to support the same?

Thanks!

**Comment by neoziro** [comment]
No it is not yet possible but I think I would allow it soon.

**Comment by neoziro** [comment]
v11 relies on [xstyled](https://www.smooth-code.com/open-source/xstyled/) currently it is not extendable but it supports all properties.
