### ISSUE TITLE
Gutter is not responsive

### ISSUE THREAD

**Issue by rafaelderolez** [smooth-code/smooth-ui#82]
I seem to be unable to do the following:

`gutter={{ xs: 10, lg: 20 }}`

This would be useful when making responsive layouts, where I wouldn't want a gutter 40px total (on mobile for example). I haven't been able to dig through the code yet, but would this be possible to add?

**Comment by neoziro** [comment]
Yeah I think it is a good idea! Yes I think it is totally possible to implement it.

**Comment by rlax** [comment]
@rafaelderolez it was implemented in v10. [New documentation for these changes](https://github.com/smooth-code/smooth-ui/commit/7bc0b8c0b5839d461c30ec454cd9d7d2a6dbcce7#diff-0713e3606c3fe96e2b5f33df29b8a570R313) 

Check out this example: https://codesandbox.io/s/5k5081lxw4
