### ISSUE TITLE
Input overflow

### ISSUE THREAD

**Issue by jacekschae** [smooth-code/smooth-ui#84]
Hello,

I updated the version of the package that shows the Form elements and it seems like there input overflow. Seems like they are longer than all the other elements and they overflow the parent

https://codesandbox.io/s/jjzvqzq31w

Am I doing something wrong here or is this a bug?

**Comment by neoziro** [comment]
Hello @jacekschae, you don't have the correct `box-sizing`, you can inject [global normalize](https://smooth-ui.smooth-code.com/docs-getting-started#global-normalize-recommended) or you can add:

```
* {
    box-sizing: border-box;
}
```

So no bug!

**Comment by jacekschae** [comment]
Thanks for pointing it out and your reply!
