### ISSUE TITLE
Modal component defaultToggled and open attribute

### ISSUE THREAD

**Issue by NYCJacob** [smooth-code/smooth-ui#89]
I am trying to have a modal default to open but allow the user to dismiss the modal.  When I use <Modal opened={true} the onClose onToggle(false) function does not close the modal.  Passing defaultToggled with Toggler doesn't seem to effect the modal being opened.  I was hoping I could pass defaultToggled={true} but that doesn't seem to be allowed.
Great project!

**Comment by neoziro** [comment]
Hello @NYCJacob, can you provide a reproduction example (using CodeSanbox for an example). Thanks!

**Comment by neoziro** [comment]
Inactive, I close it.
