### ISSUE TITLE
padding and margin of value 1 has bigger value than value 2

### ISSUE THREAD

**Issue by jacekschae** [smooth-code/smooth-ui#96]
## 💥 Regression Report

Just migrated to 8.0 and see that values for padding (p, px, py ...) and margin (m, mx, my) of value `1` have value of `64px` where value of `2` has `16px`.

Examples:

`pb: 1`

<img width="268" alt="screen shot 2019-01-17 at 09 41 11" src="https://user-images.githubusercontent.com/31179812/51305919-71bbbe00-1a3c-11e9-9476-e32b9d74c5e7.png">

`pb: 2`

<img width="268" alt="screen shot 2019-01-17 at 09 41 25" src="https://user-images.githubusercontent.com/31179812/51305930-77b19f00-1a3c-11e9-8abb-f50b8d9b4f97.png">

## Last working version

7.x

Stopped working in version: 8.0.0

## To Reproduce

Add padding or margin with value of `1`

## Expected behavior

I would expect that `p: 1` has a smaller value than `p: 2`

**Comment by neoziro** [comment]
Hello @jacekschae, thanks for the bug report. I will work on it in a couple of hours. I see what is the problem. It will be fixed soon.

**Comment by jacekschae** [comment]
Glad to help! Thanks for smoth-ui!

**Comment by jacekschae** [comment]
Thanks!
